name: Theme Switcher CD
run-name: Theme Switcher Continuous-Delivery
on:
  workflow_run:
    workflows: [Theme Switcher CI]
    types: [completed]
    branches: [main]
env:
  DEPENDENCIES_PATH: |
    ~/.cache
    ./node_modules
  DEPENDENCIES_KEY: '**/package-lock.json'
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      deployment: ${{ steps.version-bump.outputs.deploy }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure to trigger the deployment only with bumped versions
      - name: Checking version bump
        id: version-bump
        run: echo "deploy=$(./release/scripts/deploy.sh)" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: write
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.bump.outputs.deployment == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
      - name: Getting production artifacts
        uses: actions/download-artifact@v4
        with:
          name: theme-switcher-production
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: ./release/scripts/release.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  failure:
    runs-on: ubuntu-latest
    permissions: {}
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
