name: Storage Manager GitFlow
run-name: Storage Manager GitFlow ruleset
on:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        # Available merges check - See: ../../release/scripts/gitflow.sh
        if: ${{ (github.base_ref == 'main' && !contains(fromJSON('["release", "hotfix"]'), github.head_ref)) || (github.base_ref == 'develop' && !contains(fromJSON('["feature", "release", "hotfix"]'), github.head_ref)) }}
        run: ./release/scripts/gitflow.sh
